//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongDucProjectTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultPackage", Namespace="http://schemas.datacontract.org/2004/07/ATSCADA.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStampField, value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteParam", Namespace="http://schemas.datacontract.org/2004/07/ATSCADA.WebService")]
    [System.SerializableAttribute()]
    public partial class WriteParam : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName= "LongDucProjectTest.ServiceReference1")]
    public interface IATSCADAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSCADAService/Read", ReplyAction="http://tempuri.org/IATSCADAService/ReadResponse")]
        LongDucProjectTest.ServiceReference1.ResultPackage[] Read(string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSCADAService/Read", ReplyAction="http://tempuri.org/IATSCADAService/ReadResponse")]
        System.Threading.Tasks.Task<LongDucProjectTest.ServiceReference1.ResultPackage[]> ReadAsync(string[] names);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSCADAService/Write", ReplyAction="http://tempuri.org/IATSCADAService/WriteResponse")]
        LongDucProjectTest.ServiceReference1.ResultPackage[] Write(LongDucProjectTest.ServiceReference1.WriteParam[] writeParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATSCADAService/Write", ReplyAction="http://tempuri.org/IATSCADAService/WriteResponse")]
        System.Threading.Tasks.Task<LongDucProjectTest.ServiceReference1.ResultPackage[]> WriteAsync(LongDucProjectTest.ServiceReference1.WriteParam[] writeParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATSCADAServiceChannel : LongDucProjectTest.ServiceReference1.IATSCADAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATSCADAServiceClient : System.ServiceModel.ClientBase<LongDucProjectTest.ServiceReference1.IATSCADAService>, LongDucProjectTest.ServiceReference1.IATSCADAService {
        
        public ATSCADAServiceClient() {
        }
        
        public ATSCADAServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATSCADAServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATSCADAServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATSCADAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LongDucProjectTest.ServiceReference1.ResultPackage[] Read(string[] names) {
            return base.Channel.Read(names);
        }
        
        public System.Threading.Tasks.Task<LongDucProjectTest.ServiceReference1.ResultPackage[]> ReadAsync(string[] names) {
            return base.Channel.ReadAsync(names);
        }
        
        public LongDucProjectTest.ServiceReference1.ResultPackage[] Write(LongDucProjectTest.ServiceReference1.WriteParam[] writeParams) {
            return base.Channel.Write(writeParams);
        }
        
        public System.Threading.Tasks.Task<LongDucProjectTest.ServiceReference1.ResultPackage[]> WriteAsync(LongDucProjectTest.ServiceReference1.WriteParam[] writeParams) {
            return base.Channel.WriteAsync(writeParams);
        }
    }
}
